version: "3.8"

services:
  apache:
    build: .
    restart: unless-stopped
    ports:
      - "8080:80"  
    volumes:
      - .:/var/www
      - ./docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    networks:
      - app-network
    depends_on:
      - db
    environment:
      - PHP_MAX_EXECUTION_TIME=300

  db:
    image: mysql:8
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "Hol@$$2044"
      MYSQL_DATABASE: administracion_suscripciones
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - dbdata:/var/lib/mysql

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
